travis:
  secure:
    BINSTAR_TOKEN: j2DuAimbEnMfY0FDdBUSpWQ86qobdXYW4bvpTXH7UiXjQ35uFw6NETANfWCAp8BcLj1bn1u0Go2fBUWl6zqEq9X/2fwuNFeVX9qVfZr4eZyr8Gg0zgpwKZ9r7GiByQYidVtpuVO2rzkd8hCoxMbT+2zkM7t2G+GQ02HWrU0N1cYZB0x5YglrFh356V6PX9IOCTT8fGQc/ZHZ927fZU0f3xb1JQE5Q4t9YgFx2jZqhEnzMdz5+3QdQluZyCYyFBFrF/PAFue5h8sQmJau+2N6TUq2OLpbxsSUPhdn6zRyZ58CI+Go8StBehB1Mn6VlZ8I/ypj90yy8PxELoEOUYyxTSMdrTYfdquBKRKRgLQ7hgFWYqLBnfZcuRev9NVV2PuT0Ueeu0rvcd76p6usLEe1CXjJ6AtzZV5DCuqMTPU/8+I8MlIRONzen8ASZAQcN0+DTsRkdNcSUmDFyeeF+GmtBwsZo9ZrAfvj5b/5ap5dxRaxxwSkfiU4egkKY5/hv6WiiG/srLsdv/ZS9U8ESDfj6QUpjOF/MppHeWG0Ir3g5FgPyHiNtmviwKsCgmrW2c4d9U/xQE7ByM2qjQEi7EDk+RxisYKpOVu0w6+/SA4QK4n94ONIZHWgQ8g1n8cJ7Hw1MzU0hb7NWr4juk1fiT6w3tzp9s/XNvnDKhv06+Rn/fM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
