travis:
  secure:
    BINSTAR_TOKEN: Icl1lRfpjAeG5fobhZktuL0/HdMQ3WRvXEXx53ARo7HjPcFYmc63KwzJRrK8Aj6Yc1Tgr3OZhhgIr1a3Ottt67KZmObt1jVUNzMd4Xgg/t5hJFStfhxSx2LEPBrd2f7a7A+rGZnyxac64jwh29Gk3BwaI45JnGZ0zN5tUUCebIGRmdM0i7nK63zkDGD0cW7XVsfF5lmsEbGs2Vb3jZGqJGeCTVs2rrGSyEOTNg828EHlO3GBFZ1GtaPdagJoc0gPGY9qo0BH+iBLF8VmqFpDUSZT0c/1xpI1yhjFOItUF00rMHr33UQfmRgIRL3A3DvsVdf2gOGO+F0xgwSlvTcUGCwig60/ynrIm5GJXGIv+uT+fe2ZuN62jg/8Oa5bWbbfX5LuMGv6v1vCZch0K22tmugbKErg2nBJps+/dTEvYVl7QRfMORZ3ExYIS7ylcqMsC/0liYALT+bEkElYmxMW+R2KmfW1uasUisarBhf5Gc1fI1pSQAEQISRWRhIjNoZogZ8ghGaI1vq6QxLPC55nC3jIPJr9yChWCYOridzL4zAZ6lPHLDxDSF7OX1hE37f+DKh5boXCnXcbPsYTSBlwM11Fyp3mziQC93REeJ7AIzJASuGiIxuTGAHt3NquXxBiogPo6644a45NpkD6Dk+q56yHnM2krgiFWZRF+pt4s2U=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
